services:

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
     - NET_ADMIN
    environment:
     - VPN_SERVICE_PROVIDER=
     - VPN_TYPE=
     - WIREGUARD_ADDRESSES=
     - WIREGUARD_PRIVATE_KEY=
     #- LOG_LEVEL=debug
     - TZ=America/Chicago
     - UPDATER_PERIOD=24h
    ports:
     # deluge
     - 8112:8112
     - 6881:6881
     - 6881:6881/udp
     - 58846:58846 #optional
    volumes:
     - /home/name/docker/gluetun/data:/gluetun
     - /home/name/docker/init:/etc/cont-init.d

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
     - PUID=1000
     - PGID=1000
     - TZ=America/Chicago
     - DELUGE_LOGLEVEL=info #optional
    volumes:
     - /home/name/docker/deluge/config:/config
     - volume2-downloads:/downloads
     #ports:
     #  - 8112:8112
     #  - 6881:6881
     #  - 6881:6881/udp
     #  - 58846:58846 #optional
    restart: unless-stopped
    depends_on:
     - gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/name/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/name/docker/radarr/data:/config
      - volume2-movies:/movies #optional
      - volume2-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/name/docker/sonarr/data:/config
      - volume2-tv:/tv #optional
      - volume2-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Chicago
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/name/docker/overseerr/config:/app/config
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Chicago
      # get this from https://plex.tv/claim
      - PLEX_CLAIM= 
      - ADVERTISE_IP=http://YOUR-IP:32400/
    volumes:
      - /plex/database:/config
      - /plex/transcode:/transcode
      - /plex/media:/data
      - volume2-movies:/movies
      - volume2-tv:/tv-shows

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - volume2-downloads:/downloads
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - UN_LOG_FILE=/downloads/unpackerr.log
      - UN_SONARR_0_URL=http://YOUR-IP:8989
      # get this from sonarr -> settings -> general
      - UN_SONARR_0_API_KEY=
      - UN_RADARR_0_URL=http://YOUR-IP:7878
      # get this from radarr -> settings -> general
      - UN_RADARR_0_API_KEY=
      # in case you have multiple folder paths to unpack from
      #- UN_FOLDER_0_PATH=/downloads
      #- UN_FOLDER_1_PATH=/volume2-downloads

  watchlistarr:
    image: nylonee/watchlistarr
    container_name: watchlistarr
    environment:
      # get this from sonarr -> settings -> general
      SONARR_API_KEY: 
      SONARR_BASE_URL: "YOUR-IP:8989"
      # get this from radarr -> settings -> general
      RADARR_API_KEY: 
      RADARR_BASE_URL: "YOUR-IP:7878"
      # https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
      PLEX_TOKEN: 
    volumes:
      - /home/name/docker/watchlistarr/config:/app/config
    restart: unless-stopped

volumes:
  volume2-movies:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume2/media/movies
  volume2-tv:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume2/media/tv
  volume2-downloads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /volume2/downloads